---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Create fail2ban jail.local
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    backup: true
  notify: restart fail2ban

- name: Create fail2ban nginx filter
  template:
    src: nginx-limit-req.conf.j2
    dest: /etc/fail2ban/filter.d/nginx-limit-req.conf
  notify: restart fail2ban

- name: Start and enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: true