---
- name: Create n8n directory
  file:
    path: "{{ docker_data_dir }}"
    state: directory
    mode: '0755'

- name: Create n8n subdirectories
  file:
    path: "{{ docker_data_dir }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - nginx/sites-available
    - n8n/custom-nodes
    - postgres/init
    - certbot/conf
    - certbot/www

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_data_dir }}/docker-compose.yml"
    mode: '0644'

- name: Copy .env file
  template:
    src: .env.j2
    dest: "{{ docker_data_dir }}/.env"
    mode: '0600'

- name: Copy nginx configuration
  template:
    src: nginx.conf.j2
    dest: "{{ docker_data_dir }}/nginx/nginx.conf"
    mode: '0644'

- name: Copy nginx site configuration
  template:
    src: n8n.conf.j2
    dest: "{{ docker_data_dir }}/nginx/sites-available/n8n.conf"
    mode: '0644'

- name: Copy postgres init script
  template:
    src: init-n8n-db.sh.j2
    dest: "{{ docker_data_dir }}/postgres/init/init-n8n-db.sh"
    mode: '0755'

- name: Start n8n services with Docker Compose
  docker_compose:
    project_src: "{{ docker_data_dir }}"
    state: present
    pull: true

- name: Ensure Docker service is enabled and starts on boot
  systemd:
    name: docker
    enabled: true
    state: started

- name: Create Docker Compose auto-start script
  template:
    src: n8n-startup.sh.j2
    dest: /usr/local/bin/n8n-startup.sh
    mode: '0755'

- name: Create systemd service for Docker Compose auto-start
  template:
    src: n8n-docker.service.j2
    dest: /etc/systemd/system/n8n-docker.service
    mode: '0644'

- name: Enable n8n Docker Compose service
  systemd:
    name: n8n-docker
    enabled: true
    daemon_reload: true
    state: started