---
- name: Install git
  package:
    name: git
    state: present

- name: Clone or update n8n-deploy repository
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ docker_data_dir }}"
    version: "{{ git_branch }}"
    force: yes

- name: Create additional directories needed for deployment
  file:
    path: "{{ docker_data_dir }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - certbot/conf
    - certbot/www

- name: Generate .env file from template
  template:
    src: .env.j2
    dest: "{{ docker_data_dir }}/.env"
    mode: '0600'

- name: Create update script
  template:
    src: update-n8n.sh.j2
    dest: /usr/local/bin/update-n8n
    mode: '0755'

- name: Start n8n services with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ docker_data_dir }}"
    state: present
    pull: always

- name: Ensure Docker service is enabled and starts on boot
  systemd:
    name: docker
    enabled: true
    state: started

- name: Create Docker Compose auto-start script
  template:
    src: n8n-startup.sh.j2
    dest: /usr/local/bin/n8n-startup.sh
    mode: '0755'

- name: Create systemd service for Docker Compose auto-start
  template:
    src: n8n-docker.service.j2
    dest: /etc/systemd/system/n8n-docker.service
    mode: '0644'

- name: Enable n8n Docker Compose service
  systemd:
    name: n8n-docker
    enabled: true
    daemon_reload: true
    state: started