---
- name: Clean system before installing certbot
  include_tasks: cleanup.yml

- name: Install certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    clean: true

- name: Stop nginx container temporarily for certificate generation
  shell: cd {{ docker_data_dir }} && docker-compose stop nginx
  ignore_errors: true

- name: Generate SSL certificate
  command: >
    certbot certonly --standalone
    --email {{ certbot_email }}
    --agree-tos
    --no-eff-email
    --domains {{ domain_name }}
  args:
    creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"

- name: Create certbot directories in docker volume
  file:
    path: "{{ docker_data_dir }}/certbot/conf/{{ item }}/{{ domain_name }}"
    state: directory
    mode: '0755'
  loop:
    - live
    - archive

- name: Copy SSL certificates to docker volume
  copy:
    src: "/etc/letsencrypt/live/{{ domain_name }}/"
    dest: "{{ docker_data_dir }}/certbot/conf/live/{{ domain_name }}/"
    remote_src: true
    mode: preserve

- name: Copy SSL archive to docker volume
  copy:
    src: "/etc/letsencrypt/archive/{{ domain_name }}/"
    dest: "{{ docker_data_dir }}/certbot/conf/archive/{{ domain_name }}/"
    remote_src: true
    mode: preserve

- name: Start all services including nginx with SSL
  shell: cd {{ docker_data_dir }} && docker-compose up -d

- name: Create certificate renewal cron job
  cron:
    name: "Renew Let's Encrypt certificates"
    minute: "0"
    hour: "12"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/bin/certbot renew --quiet && docker-compose -f {{ docker_data_dir }}/docker-compose.yml restart nginx"